#ifndef LEMBALL_PLATFORM_DIRECTX_DSBUFFERDESC_H
#define LEMBALL_PLATFORM_DIRECTX_DSBUFFERDESC_H

struct tWAVEFORMATEX;

#define DSBCAPS_PRIMARYBUFFER 0x00000001
#define DSBCAPS_STATIC 0x00000002
#define DSBCAPS_CTRLFREQUENCY 0x00000020
#define DSBCAPS_CTRLPAN 0x00000040
#define DSBCAPS_CTRLVOLUME 0x00000080

// SIZE 0x14
struct DSBUFFERDESC {
	unsigned long dwSize;
	unsigned long dwFlags;
	unsigned long dwBufferBytes;
	unsigned long dwReserved;
	tWAVEFORMATEX* lpwfxFormat;
};

#endif
