#ifndef LEMBALL_VISOS_NETWORK_NETWORKCONSTANTS_H
#define LEMBALL_VISOS_NETWORK_NETWORKCONSTANTS_H

enum {
	NETWORK_SOCKET_HANDLE_INVALID = -1,
	NETWORK_SOCKET_ERROR = -1,
	NETWORK_SEGMENT_INDEX_INACTIVE = -1,
	NETWORK_PORT_UNASSIGNED = -1,
	NETWORK_PORT_NOT_FOUND = -1,
	NETWORK_WINDOW_MESSAGE_UNHANDLED = -1,
	NETWORK_PORT_COUNT = 0x200,
	NETWORK_BROADCAST_PORT = 0x52f2,
	NETWORK_LIFECYCLE_TIMEOUT_MS = 10000,
	NETWORK_RECEIVE_IDLE_TIMEOUT_MS = 10000,
	NETWORK_MESSAGE_SEND_WAIT_TIMEOUT_MS = 1000,
	NETWORK_PENDING_SEND_TIMEOUT_MS = 2000,
	NETWORK_GAME_STATE_RESEND_INTERVAL_MS = 2000,
	NETWORK_QUEUE_TRANSITION_TIMEOUT_MS = 2000,
	NETWORK_STARTUP_POLL_INTERVAL_MS = 100,
	NETWORK_CONNECT_TIMEOUT_MS = 4000,
	NETWORK_CRITICAL_PACKET_WAIT_TIMEOUT_MS = 4000,
	NETWORK_FILE_LOCK_RETRY_TIMEOUT_MS = 100,
	NETWORK_BROADCAST_INTERVAL_MS = 1000,
	NETWORK_CRITICAL_PACKET_RETRY_INTERVAL_MS = 1000,
	NETWORK_CLOSE_PENDING_PULSE_INTERVAL_MS = 1000,
	NETWORK_CONNECTION_MESSAGE_EXTRA_CAPACITY_BYTES = 0x101,
	NETWORK_PACKET_SIZE_BYTES = 0x400,
	NETWORK_CRITICAL_PACKET_COUNT = 100,
	NETWORK_CRITICAL_MESSAGE_CAPACITY_BYTES = 0x10,
	NETWORK_NONCRITICAL_MESSAGE_CAPACITY_BYTES = 0
};

#endif
