#ifndef LEMBALL_AI_BASE_OBJECTIDS_H
#define LEMBALL_AI_BASE_OBJECTIDS_H

#define INVALID_OBJECT_ID 0xffff
#define INVALID_OBJECT_REGISTRY_INDEX 0xffff
#define OBJECT_ID_MASK 0xffff
#define OBJECT_REGISTRY_CAPACITY 1000

enum {
	OBJECT_ID_BITMAP_BITS_PER_BYTE = 8,
	OBJECT_ID_BITMAP_BYTE_CAPACITY = 256,
	OBJECT_ID_BITMAP_BYTE_FULL_MASK = 0xff,
	OBJECT_ID_BITMAP_BYTE_INDEX_SHIFT = 3,
	OBJECT_ID_BITMAP_BIT_INDEX_MASK = OBJECT_ID_BITMAP_BITS_PER_BYTE - 1
};

#endif
