#ifndef LEMBALL_AI_BASE_AISCORECONSTANTS_H
#define LEMBALL_AI_BASE_AISCORECONSTANTS_H

enum {
	AI_SCORE_BONUS_PICKUP_POINTS = 1000,
	AI_SCORE_FLAG_PICKUP_POINTS = 2500,
	AI_SCORE_BALLOON_PICKUP_POINTS = 50,
	AI_SCORE_ENEMY_HIT_POINTS = 300,
	AI_SCORE_ENEMY_KILL_POINTS = 500,
	AI_SCORE_CATAPULT_USE_POINTS = 20,
	AI_SCORE_AMMO_PICKUP_POINTS = 50,
	AI_SCORE_DUPLICATOR_ACTIVATION_POINTS = 100,
	AI_SCORE_INVISIBLE_SWITCH_ACTIVATION_POINTS = 50,
	AI_SCORE_KEY_PICKUP_POINTS = 10,
	AI_SCORE_SHEEP_HIT_POINTS = 150,
	AI_SCORE_TIME_BONUS_PICKUP_POINTS = 250,
	AI_SCORE_BALLOON_POST_ACTIVATION_POINTS = 10,
	AI_SCORE_SWITCH_ACTIVATION_POINTS = 25,
	AI_SCORE_OBJECT_HIT_MESSAGE_POINTS = 2500
};

#endif
