#ifndef LEMBALL_AI_BASE_OBJECTACTIONS_H
#define LEMBALL_AI_BASE_OBJECTACTIONS_H

enum eAction {
	ACTION_NONE = 0,
	ACTION_TURNING = 1,
	ACTION_WALKING = 2,
	ACTION_FIRING = 3,
	ACTION_FLYING = 4,
	ACTION_HIDDEN = 5,
	ACTION_IDLE_ANIMATION = 6,
	ACTION_HIT = 7,
	ACTION_DEAD = 8,
	ACTION_FINDING_ROUTE = 9,
	ACTION_JUMPING = 10,
	ACTION_FALLING = 11,
	ACTION_WAITING_TO_SPAWN = 12,
	ACTION_PREPARING_SOMMERSAULT = 13,
	ACTION_SOMMERSAULT = 14,
	ACTION_EXTERNAL_CONTROL = 15,
	ACTION_ON_BALLOON = 16,
	ACTION_RESET_TO_STANDING = 0x11,
	ACTION_RESET_TO_STANDING_ALTERNATE = 0x12,
	ACTION_LANDING = 0x13,
	ACTION_STARTING_ROUTE = 0x14,
	ACTION_WAITING_TO_DIE = 0x15,
	ACTION_ON_CONVEYOR = 0x16,
	ACTION_RECOVERY = 0x17,
	ACTION_READY = 0x18,
	ACTION_ACTIVATING = 0x19,
	ACTION_ACTIVATED = 0x1a,
	ACTION_RUNNING = 0x1b,
	ACTION_DOOR_LOCKED_FEEDBACK = 0x1c,
	ACTION_DOOR_LOCKED = 0x1d,
	ACTION_DOOR_CLOSED = 0x1e,
	ACTION_ARRIVING = 0x1f,
	ACTION_OPENING = 0x20,
	ACTION_DOOR_OPENING = 0x20,
	ACTION_OPEN = 0x21,
	ACTION_DOOR_OPEN = 0x21,
	ACTION_CLOSING = 0x22,
	ACTION_DOOR_CLOSING = 0x22,
	ACTION_LEAVING = 0x23,
	ACTION_MOVER_WAITING_FOR_SWITCH = 0x24,
	ACTION_BALL_MOVING = 0x25,
	ACTION_BALL_EXPLODING = 0x26,
	ACTION_LOCAL_CONTROL = 0x27,
	ACTION_KEEP_CURRENT = 0x28,
	ACTION_OBJECT_READY = 24,
	ACTION_OBJECT_ACTIVATING = 25,
	ACTION_OBJECT_ACTIVATED = 26,
	ACTION_OBJECT_RUNNING = 27
};

#define ACTION_LIFT_START_RISING ACTION_ARRIVING
#define ACTION_LIFT_RISING ACTION_OPENING
#define ACTION_LIFT_LOWERING ACTION_CLOSING
#define ACTION_LIFT_START_LOWERING ACTION_LEAVING

#endif
