#ifndef LEMBALL_AI_BASE_OBJECTINTERACTIONSTATES_H
#define LEMBALL_AI_BASE_OBJECTINTERACTIONSTATES_H

enum eGroupObjectUsage {
	GROUP_OBJECT_USAGE_NONE = 0,
	GROUP_OBJECT_USAGE_GROUP = 1,
	GROUP_OBJECT_USAGE_SINGLE = 2
};

enum eGroupObjectRequestState {
	GROUP_OBJECT_REQUEST_NONE = 0,
	GROUP_OBJECT_REQUEST_REJECTED = 1,
	GROUP_OBJECT_REQUEST_ACCEPTED = 2
};

#endif
