#ifndef LEMBALL_AI_BASE_STATEMACHINE_H
#define LEMBALL_AI_BASE_STATEMACHINE_H

class CAI;
class CGameObject;
class Info;
struct StateEntry;
void StateMachine(StateEntry** p_stateTables, CAI* p_ai, CGameObject* p_object);
void UserLemming(CAI* p_ai, CGameObject* p_object);
void AIPlayerLemming(CAI* p_ai, CGameObject* p_object);
void SheepState(CAI* p_ai, CGameObject* p_object);
void EnemyState(CAI* p_ai, CGameObject* p_object);
bool PlayerNotFacingCursor(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerNotFacingTarget(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerRequestingFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerWaitingToFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerBored(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyNotFacingTarget(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyRequestingFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyWaitingToFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool GameOver(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool IsStuck(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool RequestDeath(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool NotFacingDestination(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool GotDestination(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool AtDestination(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool NotTimeUp(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool Flying(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool IsHit(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool IsJumping(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool IsFalling(CAI* p_ai, CGameObject* p_object, Info* p_info);
bool QOnBalloon(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerTurnToFaceCursor(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerTurnToFaceTarget(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerEndFiring(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartStanding(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerRandomAction(CAI* p_ai, CGameObject* p_object, Info* p_info);
void PlayerStopWalking(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartLand(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartSommersault(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Land(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartRoute(CAI* p_ai, CGameObject* p_object, Info* p_info);
void SearchRoute(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Die(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Fly(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartWalking(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StopWalking(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Walk(CAI* p_ai, CGameObject* p_object, Info* p_info);
void TurnToFaceDestination(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Hit(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Jump(CAI* p_ai, CGameObject* p_object, Info* p_info);
void Fall(CAI* p_ai, CGameObject* p_object, Info* p_info);
void ExternalControlEnd(CAI* p_ai, CGameObject* p_object, Info* p_info);
void StartBalloon(CAI* p_ai, CGameObject* p_object, Info* p_info);
void OnBalloon(CAI* p_ai, CGameObject* p_object, Info* p_info);
void EnemyTurnToFaceTarget(CAI* p_ai, CGameObject* p_object, Info* p_info);
void EnemyStartFiring(CAI* p_ai, CGameObject* p_object, Info* p_info);
void EnemyFire(CAI* p_ai, CGameObject* p_object, Info* p_info);
void EnemyEndFiring(CAI* p_ai, CGameObject* p_object, Info* p_info);
#endif
