#ifndef LEMBALL_AI_BASE_STATEMACHINE_H
#define LEMBALL_AI_BASE_STATEMACHINE_H

class CAi;
class CGameObject;
class Info;
struct StateEntry;
void StateMachine(StateEntry** p_stateTables, CAi* p_ai, CGameObject* p_object);
void UserLemming(CAi* p_ai, CGameObject* p_object);
void AiPlayerLemming(CAi* p_ai, CGameObject* p_object);
void SheepState(CAi* p_ai, CGameObject* p_object);
void EnemyState(CAi* p_ai, CGameObject* p_object);
bool PlayerNotFacingCursor(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerNotFacingTarget(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerRequestingFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerWaitingToFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool PlayerBored(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyNotFacingTarget(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyRequestingFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool EnemyWaitingToFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool GameOver(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool IsStuck(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool RequestDeath(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool NotFacingDestination(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool GotDestination(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool AtDestination(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool NotTimeUp(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool Flying(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool IsHit(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool IsJumping(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool IsFalling(CAi* p_ai, CGameObject* p_object, Info* p_info);
bool QOnBalloon(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerTurnToFaceCursor(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerTurnToFaceTarget(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerEndFiring(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartStanding(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerRandomAction(CAi* p_ai, CGameObject* p_object, Info* p_info);
void PlayerStopWalking(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartLand(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartSommersault(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Land(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartRoute(CAi* p_ai, CGameObject* p_object, Info* p_info);
void SearchRoute(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Die(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Fly(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartWalking(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StopWalking(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Walk(CAi* p_ai, CGameObject* p_object, Info* p_info);
void TurnToFaceDestination(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Hit(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Jump(CAi* p_ai, CGameObject* p_object, Info* p_info);
void Fall(CAi* p_ai, CGameObject* p_object, Info* p_info);
void ExternalControlEnd(CAi* p_ai, CGameObject* p_object, Info* p_info);
void StartBalloon(CAi* p_ai, CGameObject* p_object, Info* p_info);
void OnBalloon(CAi* p_ai, CGameObject* p_object, Info* p_info);
void EnemyTurnToFaceTarget(CAi* p_ai, CGameObject* p_object, Info* p_info);
void EnemyStartFiring(CAi* p_ai, CGameObject* p_object, Info* p_info);
void EnemyFire(CAi* p_ai, CGameObject* p_object, Info* p_info);
void EnemyEndFiring(CAi* p_ai, CGameObject* p_object, Info* p_info);
#endif
