#ifndef LEMBALL_AI_BASE_STATEMACHINE_H
#define LEMBALL_AI_BASE_STATEMACHINE_H

class CAi;
class CGameObject;
class Info;
struct StateEntry;
void StateMachine(StateEntry** p_arg0, CAi* p_arg1, CGameObject* p_arg2);
void UserLemming(CAi* p_arg0, CGameObject* p_arg1);
void AiPlayerLemming(CAi* p_arg0, CGameObject* p_arg1);
void SheepState(CAi* p_arg0, CGameObject* p_arg1);
void EnemyState(CAi* p_arg0, CGameObject* p_arg1);
bool PlayerNotFacingCursor(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool PlayerNotFacingTarget(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool PlayerRequestingFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool PlayerWaitingToFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool PlayerBored(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool EnemyNotFacingTarget(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool EnemyRequestingFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool EnemyWaitingToFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool GameOver(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool IsStuck(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool RequestDeath(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool NotFacingDestination(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool GotDestination(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool AtDestination(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool NotTimeUp(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool Flying(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool IsHit(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool IsJumping(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool IsFalling(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
bool QOnBalloon(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerTurnToFaceCursor(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerTurnToFaceTarget(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerEndFiring(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartStanding(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerRandomAction(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void PlayerStopWalking(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartLand(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartSommersault(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Land(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartRoute(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void SearchRoute(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Die(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Fly(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartWalking(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StopWalking(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Walk(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void TurnToFaceDestination(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Hit(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Jump(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void Fall(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void ExternalControlEnd(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void StartBalloon(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void OnBalloon(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void EnemyTurnToFaceTarget(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void EnemyStartFiring(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void EnemyFire(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
void EnemyEndFiring(CAi* p_arg0, CGameObject* p_arg1, Info* p_arg2);
#endif
