#ifndef LEMBALL_VISOS_ANIMATION_ANIMATIONCONSTANTS_H
#define LEMBALL_VISOS_ANIMATION_ANIMATIONCONSTANTS_H

#define ANIMATION_TIME_REALTIME 0xffffffff

enum eAnimationDirection {
	ANIMATION_DIRECTION_BACKWARD = 0,
	ANIMATION_DIRECTION_FORWARD = 1
};

#endif
