#ifndef LEMBALL_FRONTEND_BASE_FLOWPROCESSES_H
#define LEMBALL_FRONTEND_BASE_FLOWPROCESSES_H

enum eFlowProcesses {
	FLOW_NONE = 0,
	FLOW_INTRO_ANIM = 1,
	FLOW_MAIN_OPTIONS_1 = 2,
	FLOW_MAIN_OPTIONS_2 = 3,
	FLOW_PREVIEW = 4,
	FLOW_GAMEPLAY = 5,
	FLOW_ABOUT = 10,
	FLOW_NETWORK_OPTIONS = 12,
	FLOW_SUCCESS = 14,
	FLOW_FAILURE = 15,
	FLOW_PASSWORD = 16,
	FLOW_LEVEL_INTRO = 18,
	FLOW_DEMO = 19
};

#endif
