#ifndef LEMBALL_VISOS_TARGET_SOUND_DIRECTSOUND_H
#define LEMBALL_VISOS_TARGET_SOUND_DIRECTSOUND_H

enum {
	DIRECT_SOUND_ERROR_CODE_MASK = 0x0fff,
	DIRECT_SOUND_BUFFER_STATUS_PLAYING = 0x01
};

class IDirectSound;

extern IDirectSound* g_directSound;

#endif
