#ifndef LEMBALL_FRONTEND_BASE_FRONTENDLAYOUTMODE_H
#define LEMBALL_FRONTEND_BASE_FRONTENDLAYOUTMODE_H

enum eFrontendLayoutMode {
	FRONTEND_LAYOUT_STANDARD = 0,
	FRONTEND_LAYOUT_COMPACT = 1
};

#endif
