#ifndef LEMBALL_VISOS_FOUNDATION_SMALLMEMORYCONSTANTS_H
#define LEMBALL_VISOS_FOUNDATION_SMALLMEMORYCONSTANTS_H

enum {
	SMALL_MEMORY_BUCKET_COUNT = 7,
	SMALL_MEMORY_BLOCKS_PER_BITMAP_WORD = 32,
	SMALL_MEMORY_4_BYTE_BUCKET_BLOCKS_REQUESTED = 100,
	SMALL_MEMORY_8_BYTE_BUCKET_BLOCKS_REQUESTED = 192,
	SMALL_MEMORY_16_BYTE_BUCKET_BLOCKS_REQUESTED = 320,
	SMALL_MEMORY_32_BYTE_BUCKET_BLOCKS_REQUESTED = 320,
	SMALL_MEMORY_64_BYTE_BUCKET_BLOCKS_REQUESTED = 1024,
	SMALL_MEMORY_128_BYTE_BUCKET_BLOCKS_REQUESTED = 512,
	SMALL_MEMORY_256_BYTE_BUCKET_BLOCKS_REQUESTED = 128
};

#endif
