#ifndef LEMBALL_VIEWS_DISPLAY_DISPLAYQUITSTATE_H
#define LEMBALL_VIEWS_DISPLAY_DISPLAYQUITSTATE_H

enum eDisplayQuitResult {
	DISPLAY_QUIT_NONE = 0,
	DISPLAY_QUIT_CHANGE_FLOW = 1,
	DISPLAY_QUIT_APPLICATION = 2
};

#endif
