#ifndef LEMBALL_AI_BASE_LEVELVERSIONS_H
#define LEMBALL_AI_BASE_LEVELVERSIONS_H

enum eLevelFormatVersion {
	LEVEL_VERSION_UNVERSIONED = 0,
	LEVEL_VERSION_LAST_WITHOUT_OBJECT_IDS = 1,
	LEVEL_VERSION_LAST_WITHOUT_SERIALIZED_SWITCH_DATA = 1,
	LEVEL_VERSION_WITH_LIFTS = 3,
	LEVEL_VERSION_LAST_WITHOUT_DOOR_TYPES = 2,
	LEVEL_VERSION_WITH_PLAYER_COUNTS = 4,
	LEVEL_VERSION_WITH_LIFT_ENDPOINTS = 5,
	LEVEL_VERSION_LAST_WITHOUT_MOVER_PATHS = 5,
	LEVEL_VERSION_WITH_AMMO_COUNTS = 8,
	LEVEL_VERSION_WITH_REPEATABLE_INVISIBLE_SWITCHES = 9,
	LEVEL_VERSION_WITH_INITIAL_ICE_SWITCH_STATE = 10,
	LEVEL_VERSION_CURRENT = LEVEL_VERSION_WITH_INITIAL_ICE_SWITCH_STATE
};

#endif
