#ifndef LEMBALL_FRONTEND_RESOURCES_CDLOADANIMDRAW_H
#define LEMBALL_FRONTEND_RESOURCES_CDLOADANIMDRAW_H

// SIZE 0x04
// VTABLE: LEMBALL 0x00497c94
class CdLoadAnimDraw {
public:
	virtual void Draw() = 0;
};

#endif
