#ifndef LEMBALL_SCAFFOLD_COMMON_H
#define LEMBALL_SCAFFOLD_COMMON_H

typedef unsigned char undefined;
typedef unsigned short undefined2;
typedef unsigned int undefined4;
typedef unsigned int size_t;

#define DEBUG_SENTINEL ((int) 0xaa55aa55)
#define DEBUG_SENTINEL_WORD ((short) 0xaa55)
#define VS_UNINITIALISED DEBUG_SENTINEL

typedef int eAction;
typedef int eBroadcastTypes;
typedef int eCursorDisplayType;
typedef int eDestinationType;
typedef int eFireRequestState;
typedef int eFlowProcesses;
typedef int eGroupState;
typedef int eObjectType;
typedef int eOwner;
typedef int ePaletteTypes;
typedef int ePauseWindowMessages;
typedef int eSoundEffect;
typedef int NetworkErrors;
typedef int NetworkEvents;
struct _Filet;
struct FILE;

class AiCoord;
class AiDestinationEntry;
class AiDestinationList;
class C3DVector;
class Vector;
class Fixed;
class AckMessage;
class Ai;
class AnimsManager;
class Anim;
class Arena;
class C2D;
class BaseCommonSocket;
class BaseNetwork;
class BasePacket;
class BasePacketBuff;
struct BasePacketHeader;
class BaseQueue;
class BaseQueueHandler;
class BaseRemap;
class BasePalManager;
class BaseStat;
class BaseSocket;
class BaseSoundDevice;
class Broadcast;
class BroadcastMessage;
class Bucket;
class Bullet;
class Connect;
class ChangeList;
class CopyText;
class DepressedButton;
class FontTable;
class FormationManager;
class GenericGroup;
class GenericGroupManager;
class GrafPort;
class GraphicButton;
class GunButtons;
class GunController;
struct GunControllerJunction;
class HiliteButtons;
class HiliteController;
struct HiliteControllerJunction;
class HiliteWindow;
class IntroAnimAnimWindow;
class IntroAnimDrawer;
class PasswordDrawer;
class PasswordHiliteWindow;
class Panel;
class PanelButton;
class PanelButtonHotAreaSubobject;
class PanelLemming;
class PanelPauseButton;
class PanelPauseButtonHotAreaSubobject;
class PauseWindow;
class PauseWindowFreeVramInterface;
class PauseWindowFreeVramSubobject;
class PauseWindowHotAreaSubobject;
class PauseWindowQueueSubobject;
class ReceiveWindowState;
class PreviewDrawer;
class BaseFrontendDrawer;
class FrontendResourceLoader;
class CdLoadAnim;
class SuccFail;
class SuccFailAnimWindow;
class SuccFailDrawer;
struct HotAreaElement;
class HotAreaHandler;
class HotAreaList;
class String;
class SmallMemory;
class SoundManager;
class Text;
class TextManager;
class TrackWindow;
class TrackWindowHotAreaSubobject;
class TrackerButton;
class TrackerButtonHotAreaSubobject;
class GameObject;
class Game;
class Gdi;
class GWnd;
class EnemyGroup;
class EnemyGroupManager;
class EditString;
class EntryHandler;
class GameObjectMess;
class GameFlaggedMessage;
class GlobalGameObject;
class Hand;
class HandManager;
class Ice;
class IceManager;
class Laser;
class LaserManager;
class LemmingAnimsManager;
class Line;
class MBlock;
class MramBlock;
class MessFailedConnect;
class MessGoConnect;
class MessOkConnect;
class MessReqConnect;
class MessReqNewPort;
class MasterInput;
class MogDir;
class MogloadArena;
class MogRes;
class NetworkAddress;
class NetworkMessage;
class NetworkGameMessage;
class NetworkGameStage;
class GameRejectMessage;
class GameAcceptMessage;
class ObjectManager;
class ObjectChangeStateMess;
class ObjectDiesMess;
class ObjectHitMess;
class ObjectPosMess;
class PlayerLemming;
class PlayerLemmingGroup;
class PlayerLemmingGroupManager;
class PlayThruAnim;
class Primitive;
struct Pt3;
class PulseMessage;
class PvBackBuffSurface;
class PvButton;
class PvGdiBitmap;
class PvMusicDevice;
class PvGWnd;
class PvScrollableSurface;
class PvSurface;
class PvZBuffSurface;
class Rect3;
class Remap;
class RamArena;
class ReadCBuff;
class ReadCmsBuff;
class ReadMsBuff;
class ReadNcBuff;
class ReadNcmsBuff;
class ReadPacket;
class ReadPacketBuff;
class ReadSocket;
class RemoveObjectMess;
class RawRead;
class RequestActionMess;
class RequestCancelMess;
class RequestReplyMess;
struct ResourceTypeList;
class ResBase;
class ResBaseList;
class ResAnim;
class ResBin;
class ResBitmap;
class ResEffect;
class ResFont;
class ResInt;
class ResMovie;
class ResPalette;
class ResString;
class ResZrle;
class SheepGroup;
class SheepGroupManager;
class Sheep;
class SolidRect;
class StatManager;
class StaticAnim;
class Surface;
class SpriteWindow;
class ViewData;

struct VsRange;

class VsOStream;
class WriteCBuff;
class WriteNcBuff;
class WritePacket;
class WritePacketBuff;
class WriteSocket;
class Wnd;
struct StateEntry;
struct EventRecords;
struct EventRecord;
struct Chunk;
struct ChunkInfo;

struct Coord3d;
class Info;
struct Message;
struct CoordPair;
// SIZE 0x18
struct MenuList {
	char* m_name;    // 0x00
	int m_commandId; // 0x04
	int m_action;    // 0x08
	int m_enabled;   // 0x0c
	int m_unk10;     // 0x10
	int m_unk14;     // 0x14
};

struct Rect;
struct LoadEnemyData;
struct LoadEnemyDataAdditionalAction;
struct LoadSheepData;
struct WaypointInformation;
class VsTrig;

class AiCursor;
class Ammo;
class AnimSpecial;
struct AnimSpecialEntry;
class AnimWnd;
class Ball;
class BallManager;
class Balloon;
class BalloonPost;
class BaseCursor;
class BaseFrontendProcess;
class BaseGlobalObject;
class BaseObjectManager;
class BigBitmap;
class Bitmap;
class BitmapRes;
class BitmapResBase;
class Bonus;
class BulletManager;
class C2DHotAreaSubobject;
class C2DQueueSubobject;
class C2DReceiveWindowStateSubobject;
class Catapult;
class ClipRect;
class Collectable;
class CollectableManager;
class CopyColourToBackBuff;
class CopyToBackBuff;
class Crate;
class Critical;
class Cursor;
class Demo;
class Door;
class DoorManager;
class Drawer;
class DrawingMark;
class Duplicator;
class Enemy;
class FileBaseSocket;
class FileBroadcast;
class FileCommonSocket;
class FileConnect;
class FileNetwork;
class FileNetworkAddress;
class FileOpenManagement;
class FileReadSocket;
class FileRwSocket;
class FileWriteSocket;
class Flag;
class Frames;
class GameStateMessage;
class GameStatus;
class GdiDevice;
class GodManager;
class Ground;
class GroundAnim;
struct GroundAnimEntry;
class GroundArray;
class GunButton;
class HeaderMessage;
class Headers;
class IntroAnim;
class InvisibleSwitch;
class InvisibleSwitchManager;
struct InvisibleSwitchTarget;
class Key;
class LemmingAnimsLoadSubobject;
class LevelLoader;
class Lift;
struct LiftEndpointRecord;
class LiftManager;
struct LoadBlockHeader;
class Main2DDisplay;
class MainOptions1;
class MainOptions1Drawer;
class MainOptions2;
class MainOptions2Drawer;
class Map;
class Maze;
class Mine;
class MineManager;
class Move3d;
class Mover;
class MoverManager;
class NetworkFile;
class NetworkManager;
class NetworkOptionsDrawer;
class NetworkOptionsProc;
class Node;
class NodeManager;
struct NodeNeighbour;
class ObjSq;
class OpenCount;
class PadToButton;
struct PadToButtonEntry;
class PaintGun;
class PaintGunManager;
class PaletteManager;
class PasswordProc;
class PbButton;
class PbNetworkGame;
class PopActive;
class PortsMessage;
struct PreInit;
class Preview;
struct PreviewData;
class Prims;
class BaseProcess;
class PushActive;
class PvAnimWnd;
class PvFontTable;
class PvWnd;
class RepeatAnim;
class ResBool;
class ResCol;
class ResImage;
class ResPatch;
class ResPres;
class ResTune;
class Rocket;
class RocketManager;
class Slinky;
class SlinkyManager;
struct Solution;
class SoundView;
class Switch;
struct SwitchEntry;
class TargetAbout;
class TargetAboutScreen;
class TargetDibContext;
class TargetDirectDrawContext;
class TargetDirectDrawDriver;
class TargetDirectDrawSurfaceContext;
class TargetDirectSoundDevice;
class TargetDirectSoundEffect;
class TargetDisplayDibDriver;
class TargetDrawingContext;
class TargetFramedButton;
class TargetGraphicsDriver;
struct TargetGraphicsSystemState;
class TargetInputTextButton;
struct TargetInputTranslationEntry;
class TargetMasterInputItem;
class TargetNetworkWindow;
struct TargetObjectClipCell;
struct TargetObjectClipGrid;
class TargetPlanarDisplayDibDriver;
class TargetPlatformServices;
class TargetResourceButton;
struct TargetSpriteGroundLookup;
class TargetTextButton;
struct TargetTextLine;
struct TargetTextLineBuffer;
class TargetTextWindow;
class TargetWaveEffect;
class TargetWaveSoundDevice;
struct TargetWinGDrawCodecState;
class TcpIpBroadcast;
class TcpIpCommonSocket;
class TcpIpConnect;
class TcpIpNetwork;
class TcpIpNetworkAddress;
class TcpIpReadSocket;
class TcpIpRwSocket;
class TcpIpWriteSocket;
class TheBalloonPost;
class TimeBonus;
class TimeStat;
class TimedAnim;
class TimedQueue;
class ToggleButton;
class Tower;
class Trampoline;
class TrampolineManager;
class Translator;
class TransportObjectMess;
class TrapDoor;
class TrapDoorManager;
class UserActionMessage;
class VsDebugStreambuf;
class VsIOs;
class VsMath;
struct VsPoint;
class VsRect;
struct VsSize;
class VsStreambuf;
class WindowsCursorMotionState;
class ZBuffClear;
class Zrle;
typedef int eBulletType;
typedef int eGameStates;
typedef int eGameStateStages;
typedef int swMessage;
typedef int eLiftActivateType;
typedef int eSkill;
class LoadUpdate;
class EnemyLemmingUnion;
class Circle;
class FilledCircle;
class Point;
class ScreenScroll;
class ZBuffScroll;
class LoadDefaultBlox;
struct LoadGroundName;
struct LoadGroundSurfaceData;
typedef int eGameStatus;
struct ChangeListItem {
	ChangeListItem();
	short width;
	short height;
	short x;
	short y;
	unsigned int drawMark;
};

struct Boffset {
	unsigned short wWord;
	unsigned short wBit;
};

struct Har4 {
	unsigned int m_value;
	Har4(unsigned int v = 0) : m_value(v) {}
};
struct Hex {
	unsigned int m_value;
	Hex(unsigned int v = 0) : m_value(v) {}
};
struct Hex8 {
	unsigned int m_value;
	Hex8(unsigned int v = 0) : m_value(v) {}
};
struct Rname {
	unsigned int m_value;
	Rname(unsigned int v = 0) : m_value(v) {}
};
typedef unsigned char byte;
typedef int eEnemyStateRules;
typedef int eEnemyStateActions;
typedef unsigned short word;
struct Message {
	unsigned short type;
	unsigned short reserved;
	unsigned int time;
	int code;
	void* payload;
	void* source;
};

typedef int eUserActions;
typedef int eUserActionStages;
#endif
