#ifndef LEMBALL_VISOS_FOUNDATION_FIXEDPOINT_H
#define LEMBALL_VISOS_FOUNDATION_FIXEDPOINT_H

enum {
	FIXED_POINT_FRACTION_BITS = 12,
	FIXED_POINT_ONE = 0x1000
};

#define FIXED_POINT_FRACTION_MASK 0xfff
#define FIXED_POINT_INTEGER_MASK 0xfffff000

#endif
