#ifndef LEMBALL_VISOS_FOUNDATION_PROCESSEXITCODES_H
#define LEMBALL_VISOS_FOUNDATION_PROCESSEXITCODES_H

enum eProcessExitCode {
	VISOS_FATAL_EXIT_CODE = 0xaaaa,
	VISOS_THREAD_START_FAILURE_EXIT_CODE = 0xbbbb
};

#endif
