#ifndef LEMBALL_VISOS_FOUNDATION_RANDOMCONSTANTS_H
#define LEMBALL_VISOS_FOUNDATION_RANDOMCONSTANTS_H

enum eRandomSeedParameters {
	RANDOM_SEED_MULTIPLIER = 41,
	RANDOM_SEED_INCREMENT = 31,
	RANDOM_SEED_MASK = (1 << 23) - 1
};

#endif
