#ifndef LEMBALL_VISOS_FOUNDATION_TEXTADVANCEFLAGS_H
#define LEMBALL_VISOS_FOUNDATION_TEXTADVANCEFLAGS_H

enum eTextAdvanceFlags {
	TEXT_ADVANCE_X_POSITIVE = 0x20,
	TEXT_ADVANCE_X_NEGATIVE = 0x40,
	TEXT_ADVANCE_Y_NEGATIVE = 0x80,
	TEXT_ADVANCE_Y_POSITIVE = 0x100,
	TEXT_ADVANCE_USE_CUSTOM_OFFSETS = 0x200,
	TEXT_ADVANCE_HORIZONTAL_MASK = TEXT_ADVANCE_X_NEGATIVE | TEXT_ADVANCE_X_POSITIVE,
	TEXT_ADVANCE_VERTICAL_MASK = TEXT_ADVANCE_Y_NEGATIVE | TEXT_ADVANCE_Y_POSITIVE,
	TEXT_ADVANCE_BEFORE_GLYPH_MASK = TEXT_ADVANCE_X_NEGATIVE | TEXT_ADVANCE_Y_NEGATIVE
};

#endif
